remote_theme: "mmistakes/minimal-mistakes@4.16.4"
minimal_mistakes_skin: "mint"
#Site Settings
locale: "en-US"
title: "Learning Machine Learning"
title_separator: "_"
name: "Margaret Lazarovits"
description: "Welcome to KU Physics's machine learning club! Scroll down to learn more."
masthead_title: "Learning Machine Learning"





#gems
plugins:
  - jekyll-include-cache
  - jek
