remote_theme: "mmistakes/minimal-mistakes@4.16.4"
minimal_mistakes_skin: "mint"

#Site Settings
locale: "en-US"
title: "Learning Machine Learning"
title_separator: "-"
name: &name "Margaret Lazarovits"
description: "Welcome to KU Physics's machine learning club! Scroll down to learn more."
masthead_title: "Learning Machine Learning"
url: "https://LearningMachineLearning.github.io"
baseurl: "/LearningMachineLearning"
repository: "mlazarovits/LearningMachineLearning"
teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"

search: true
analytics:
  provider: "google"
  google:
    tracking_id: "UA-141268050-1"


timezone: America/Chicago

teaser: /assets/images/teaser.jpg

# Site Author
author:
  name             : "Want to Learn More?"
  #avatar           : "/assets/images/Graduation-14.jpg"
  bio              : "Email us below, or sign up for our meetings!"
  location         : "University of Kansas"
  links:
    - label: "Email Us"
      icon: "fas fa-fw fa-envelope"
      url: mailto:mlazarovits@gmail.com
    - label: "Sign Up Here!"
      icon: "fas fa-fw fa-angle-right"
      url: "https://rockchalkcentral.ku.edu/organization/learningmachinglearning"



#Reading files
include:
  - _pages

# collections:
#   portfolio:
#     output: true


#Defaults
defaults:
  #_pages
- scope:
    path: "_pages"
    type: pages
  values:
    layout: single
    author_profile: true
  #_posts
- scope:
    path: ""
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true  
    

#gems
plugins:
  - jekyll-include-cache

