remote_theme: "mmistakes/minimal-mistakes@4.16.4"
minimal_mistakes_skin: "mint"
#Site Settings
locale: "en-US"
title: "Learning Machine Learning"
title_separator: "-"
name: "Margaret Lazarovits"
description: "Welcome to KU Physics's machine learning club! Scroll down to learn more."
masthead_title: "Learning Machine Learning"
url: "https://LearningMachineLearning.github.io"
baseurl: "/LearningMachineLearning"
repository: "mlazarovits/LearningMachineLearning"
teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"

search: true
analytics:
  provider: "google"
  google:
    tracking_id: "UA-141268050-1"


timezone: America/Chicago


# Site Author
author:
  name             : "Contact Us"
  #avatar           : "/assets/images/Graduation-14.jpg"
  bio              : "fill in bio l8r"
  location         : "University of Kansas"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:mlazarovits@gmail.com



#Reading files
include:
  - _pages


#Defaults
defaults:
  #_pages
- scope:
    path: " "
    type: pages
  values:
    author_profile: true
    layout: single
    

#gems
plugins:
  - jekyll-include-cache

